### ISSUE TITLE
scisprint20#2

### ISSUE THREAD

**Issue by YenPeiChen07** [yungyuc/turgon#13]
This ticket is to collect information for the `libst` sprint (scisprint20#2). To join the sprint please comment on this issue with your name (in addition to GitHub account).

- Date: Sat, 28th March, 2020
- Time: 14:00 -- 16:00
- Venue: Online Zoom (TBD)
- Gitter: https://gitter.im/yyc-turgon/community

Last sprint: https://github.com/yungyuc/turgon/issues/10

Last time the progress was to the last phase of environment setup.

# Work items

- Trace code (with the environment built).
- Find questions to the code base.
- Release process and scripts.
- Add build instructions.
- Add documentation structure.
- One-dimensional grid.
- Element abstraction for the space-time conservation element and solution element (CESE) method.
- Develop validating unit-tests cases for the two model problems:
  - Linear wave.
  - Inviscid Burgers' equation.
- Make a prototype to allow writing solvers in Python.

# Prerequisites

- Everyone gets the environment built before the sprint.
- Understand Python.

# Attendees
| Github | name |
| --------- | -------- |
| @YenPeiChen07 | Jenny Yen|
| @yungyuc  | Yung-Yu |
| @yuko29 | Yu-Fang Hu |
| @OhMyBuggg | Po-Yu Liu |
| @Joechiaotung | Chiung-I Wu |
| @sophiiim05g | Shu-Fen Yu |
| @plChao | Ping-Lien Chao |

**Comment by yungyuc** [comment]
Thanks @YenPeiChen07.  Yung-Yu signs up.

Could you add a table of attendees like the one in #10?

**Comment by yuko29** [comment]
@yuko29 Yu-Fang Hu

**Comment by OhMyBuggg** [comment]
@ohmybugg Po-Yu Liu

**Comment by OhMyBuggg** [comment]
Po-Yu Liu

**Comment by Joechiaotung** [comment]
@Joechiaotung Chiung-I Wu

**Comment by sophiiim05g** [comment]
Shu-Fen Yu

**Comment by plChao** [comment]
Ping-Lien Chao

**Comment by yungyuc** [comment]
Hi everyone.  Thanks for signing up again.

I plan to try with Zoom the video conferencing tool for this online sprint.  It will be clumsy to do 1:1 discussion using Zoom, so we will also need the gitter chat room to facilitate discussions: https://gitter.im/yyc-turgon/community.  Please make sure you are in that room during the sprint.

**Comment by yungyuc** [comment]
Thank you all for joining the online sprint today.  Hopefully you had good two hours of coding.

If you have any further questions please feel free to ask in the gutter.  I can also add you to the turgon slack channel if you want.
