### ISSUE TITLE
building turgon on Ubuntu 18.04

### ISSUE THREAD

**Issue by plChao** [yungyuc/turgon#15]
Thanks yy hosting sprint!
When I was building project in Ubuntu, I encounter some problem because there are some difference between CI environment and Ubuntu local environment.
These are notes about how to build in Ubuntu 18.04 environment.
First, we need to install some dependency in order to run `make pytest` in `/spacetime`.
Run the command below to install dependency.
```
sudo apt-get -qy install \
     sudo curl git build-essential make cmake libc6-dev gcc-7 g++-7 \
     python3.7 python3.7-dev python3.7-venv
sudo rm /usr/bin/python3
sudo ln -s python3.7 /usr/bin/python3
sudo apt install python3-pip
sudo pip3 install -U pip
sudo pip3 install -U numpy pytest setuptools cmake
```
Second, we need to install some dependency by running `./install.sh everything` in `/contrib/depend`

Now, we can run `make pytest` in `/spacetime` to check if the project can run well.

**Comment by yungyuc** [comment]
I think it is good to organize the procedures in a script file (or a couple of them) (they may be placed in `contrib/depend/`), and write down the description in a `README`.  How do you think?

**Comment by plChao** [comment]
I think it's a good idea ! I add a function in install.sh in order that programmer can run `./install.sh ubuntu_1804` to execute the commands.
