### ISSUE TITLE
pytest warning

### ISSUE THREAD

**Issue by j8xixo12** [yungyuc/turgon#28]
I noticed that pytest log showed 23 warnings , here are some waring message

> =============================== warnings summary ===============================
tests/test_celm_selm.py:104
  /home/runner/work/turgon/turgon/spacetime/tests/test_celm_selm.py:104: DeprecationWarning: invalid escape sequence \(
    "Celm\(xindex=2\)::move_at\(offset=-1\): xindex = 1 "
tests/test_celm_selm.py:105
  /home/runner/work/turgon/turgon/spacetime/tests/test_celm_selm.py:105: DeprecationWarning: invalid escape sequence \[
    "outside the interval \[2, 23\)",
tests/test_celm_selm.py:112
  /home/runner/work/turgon/turgon/spacetime/tests/test_celm_selm.py:112: DeprecationWarning: invalid escape sequence \(
    "Celm\(xindex=22\)::move_at\(offset=1\): xindex = 23 "
.
.
.

It seems to be caused by the regular expression in assert message.

**Comment by yungyuc** [comment]
Yes, but the warning looks benign, so far.  Feel free to file a PR to fix it, but I think it's also OK to spend time on other points and leave this issue open.

**Comment by yungyuc** [comment]
@j8xixo12 do you think we should try to fix this warning issue?

**Comment by j8xixo12** [comment]
Maybe I can try to fix these warnings!

**Comment by yungyuc** [comment]
Fixed by #37.
