### ISSUE TITLE
scisprint20#3

### ISSUE THREAD

**Issue by yuko29** [yungyuc/turgon#31]
This ticket is to collect information for the libst sprint (scisprint20#3). To join the sprint please comment on this issue with your name (in addition to GitHub account).

Date: Sat, 24th October, 2020
Time: 13:30 -- 16:30
Venue: R101, Engineering Bldg. 4, NCTU
Discord: https://discord.gg/P9U7PFv
Last sprint: [#13](https://github.com/yungyuc/turgon/issues/13)

# Work items

- Error analysis for the linear advection equation 

# Prerequisites

- Everyone gets the environment built before the sprint.
- Understand Python.

# Attendees

| Github | name |
| ------ | ---- |
|  @yungyuc    |  Yung-Yu  |
| @j8xixo12     | Chun-Hsu |
| @yuko29      | Yu-Fang    |

**Comment by yungyuc** [comment]
No we are on it!
