### ISSUE TITLE
can't build modmesh, 

### ISSUE THREAD

**Issue by zhdd80** [yungyuc/turgon#40]
12%] Building CXX object CMakeFiles/_libst.dir/src/python/libst.cpp.o
In file included from /usr/local/include/modmesh/python/python.hpp:36,
                 from /home/zdd/turgon/spacetime/include/spacetime/python.hpp:11,
                 from /home/zdd/turgon/spacetime/src/python/libst.cpp:6:
/usr/local/include/modmesh/python/common.hpp: In member function ‘modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::wrapper_type& modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::expose_SimpleArray(const char*, Func&&)’:
/usr/local/include/modmesh/python/common.hpp:311:47: error: ‘invoke_result_t’ in namespace ‘std’ does not name a template type
  311 |         using array_reference = typename std::invoke_result_t<Func, wrapped_type &>;
      |                                               ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:311:47: note: ‘std::invoke_result_t’ is only available from C++17 onwards
/usr/local/include/modmesh/python/common.hpp:312:41: error: ‘array_reference’ was not declared in this scope
  312 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                         ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:312:56: error: template argument 1 is invalid
  312 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                                        ^
/usr/local/include/modmesh/python/common.hpp:314:75: error: ‘<declaration error>’ is not a template [-fpermissive]
  314 | ing array_type = typename std::remove_reference<array_reference>::type;
      |                                                                 ^~

/usr/local/include/modmesh/python/common.hpp:319:46: error: ‘array_reference’ does not name a type
  319 |                 [&f](wrapped_type & self) -> array_reference
      |                                              ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:321:86: error: template argument 1 is invalid
  321 | pped_type & self, py::array_t<typename array_type::value_type> & ndarr)
      |                                                              ^

/usr/local/include/modmesh/python/common.hpp: In lambda function:
/usr/local/include/modmesh/python/common.hpp:323:21: error: ‘array_reference’ is not captured
  323 |                     array_reference this_array = f(self);
      |                     ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:321:20: note: the lambda has no capture-default
  321 |                 [&f](wrapped_type & self, py::array_t<typename array_type::value_type> & ndarr)
      |                    ^
/usr/local/include/modmesh/python/common.hpp:312:41: note: ‘<typeprefixerror>array_reference’ declared here
  312 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                         ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:324:25: error: ‘this_array’ was not declared in this scope
  324 |                     if (this_array.nbytes() != static_cast<size_t>(ndarr.nbytes()))
      |                         ^~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:324:74: error: request for member ‘nbytes’ in ‘ndarr’, which is of non-class type ‘int’
  324 |         if (this_array.nbytes() != static_cast<size_t>(ndarr.nbytes()))
      |                                                              ^~~~~~

/usr/local/include/modmesh/python/common.hpp:327:38: error: request for member ‘nbytes’ in ‘ndarr’, which is of non-class type ‘int’
  327 |                         msg << ndarr.nbytes() << " bytes of input array differ from "
      |                                      ^~~~~~
/usr/local/include/modmesh/python/common.hpp:331:36: error: no matching function for call to ‘makeSimpleArray(int&)’
  331 |                     makeSimpleArray(ndarr).swap(this_array);
      |                     ~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/modmesh/python/common.hpp:194:23: note: candidate: ‘template<class T> modmesh::SimpleArray<U> modmesh::python::makeSimpleArray(pybind11::array_t<T>&)’
  194 | static SimpleArray<T> makeSimpleArray(pybind11::array_t<T> & ndarr)
      |                       ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:194:23: note:   template argument deduction/substitution failed:
/usr/local/include/modmesh/python/common.hpp:331:36: note:   mismatched types ‘pybind11::array_t<T>’ and ‘int’
  331 |                     makeSimpleArray(ndarr).swap(this_array);
      |                     ~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/modmesh/python/common.hpp:331:49: error: ‘this_array’ was not declared in this scope
  331 |                     makeSimpleArray(ndarr).swap(this_array);
      |                                                 ^~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp: In member function ‘modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::wrapper_type& modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::expose_SimpleArrayAsNdarray(const char*, Func&&)’:
/usr/local/include/modmesh/python/common.hpp:344:47: error: ‘invoke_result_t’ in namespace ‘std’ does not name a template type
  344 |         using array_reference = typename std::invoke_result_t<Func, wrapped_type &>;
      |                                               ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:344:47: note: ‘std::invoke_result_t’ is only available from C++17 onwards
/usr/local/include/modmesh/python/common.hpp:345:41: error: ‘array_reference’ was not declared in this scope
  345 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                         ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:345:56: error: template argument 1 is invalid
  345 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                                        ^
/usr/local/include/modmesh/python/common.hpp:347:75: error: ‘<declaration error>’ is not a template [-fpermissive]
  347 | ing array_type = typename std::remove_reference<array_reference>::type;
      |                                                                 ^~

/usr/local/include/modmesh/python/common.hpp:354:86: error: template argument 1 is invalid
  354 | pped_type & self, py::array_t<typename array_type::value_type> & ndarr)
      |                                                              ^

/usr/local/include/modmesh/python/common.hpp: In lambda function:
/usr/local/include/modmesh/python/common.hpp:356:21: error: ‘array_reference’ is not captured
  356 |                     array_reference this_array = f(self);
      |                     ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:354:20: note: the lambda has no capture-default
  354 |                 [&f](wrapped_type & self, py::array_t<typename array_type::value_type> & ndarr)
      |                    ^
/usr/local/include/modmesh/python/common.hpp:345:41: note: ‘<typeprefixerror>array_reference’ declared here
  345 |         static_assert(std::is_reference<array_reference>::value, "this_array_reference is not a reference");
      |                                         ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:357:25: error: ‘this_array’ was not declared in this scope
  357 |                     if (this_array.nbytes() != static_cast<size_t>(ndarr.nbytes()))
      |                         ^~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:357:74: error: request for member ‘nbytes’ in ‘ndarr’, which is of non-class type ‘int’
  357 |         if (this_array.nbytes() != static_cast<size_t>(ndarr.nbytes()))
      |                                                              ^~~~~~

/usr/local/include/modmesh/python/common.hpp:360:38: error: request for member ‘nbytes’ in ‘ndarr’, which is of non-class type ‘int’
  360 |                         msg << ndarr.nbytes() << " bytes of input array differ from "
      |                                      ^~~~~~
/usr/local/include/modmesh/python/common.hpp:364:21: error: ‘this_array’ was not declared in this scope
  364 |                     this_array.swap(makeSimpleArray(ndarr));
      |                     ^~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:364:52: error: no matching function for call to ‘makeSimpleArray(int&)’
  364 |                     this_array.swap(makeSimpleArray(ndarr));
      |                                     ~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/modmesh/python/common.hpp:194:23: note: candidate: ‘template<class T> modmesh::SimpleArray<U> modmesh::python::makeSimpleArray(pybind11::array_t<T>&)’
  194 | static SimpleArray<T> makeSimpleArray(pybind11::array_t<T> & ndarr)
      |                       ^~~~~~~~~~~~~~~
/usr/local/include/modmesh/python/common.hpp:194:23: note:   template argument deduction/substitution failed:
/usr/local/include/modmesh/python/common.hpp:364:52: note:   mismatched types ‘pybind11::array_t<T>’ and ‘int’
  364 |                     this_array.swap(makeSimpleArray(ndarr));
      |                                     ~~~~~~~~~~~~~~~^~~~~~~
In file included from /home/zdd/turgon/spacetime/src/python/libst.cpp:6:
/home/zdd/turgon/spacetime/include/spacetime/python.hpp: In function ‘void spacetime::python::initialize(pybind11::module&)’:
/home/zdd/turgon/spacetime/include/spacetime/python.hpp:88:56: error: no match for call to ‘(modmesh::python::OneTimeInitializer<spacetime::python::init_tag>) (pybind11::module&, bool, void (&)(pybind11::module&))’
   88 |     modmesh::python::OneTimeInitializer<init_tag>::me()(mod, true, detail::initialize_impl);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/zdd/turgon/spacetime/include/spacetime/python.hpp:11,
                 from /home/zdd/turgon/spacetime/src/python/libst.cpp:6:
/usr/local/include/modmesh/python/python.hpp:69:29: note: candidate: ‘modmesh::python::OneTimeInitializer<T>& modmesh::python::OneTimeInitializer<T>::operator()(pybind11::module&, const std::function<void(pybind11::module_&)>&) [with T = spacetime::python::init_tag; pybind11::module = pybind11::module_]’
   69 |     OneTimeInitializer<T> & operator()(
      |                             ^~~~~~~~
/usr/local/include/modmesh/python/python.hpp:69:29: note:   candidate expects 2 arguments, 3 provided
make[2]: *** [CMakeFiles/_libst.dir/build.make:82: CMakeFiles/_libst.dir/src/python/libst.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:204: CMakeFiles/_libst.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by yungyuc** [comment]
It is not helping to post unformatted error logs.  Please state clearly what is your problem and provide analysis.
