### ISSUE TITLE
About pthread_create 

### ISSUE THREAD

**Issue by Joechiaotung** [yungyuc/turgon#9]
When I use command `cmake /home/joe/turgon/spacetime/` and I can't figure out why pthread_create can't be find.
the following is log from terminal after I type.
` CMake Error at CMakeLists.txt:5 (cmake_policy):
  Policy "CMP0074" is not known to this version of CMake.`
`-- The C compiler identification is GNU 7.4.0`
`-- The CXX compiler identification is GNU 7.4.0`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Check for working CXX compiler: /usr/bin/c++`
`-- Check for working CXX compiler: /usr/bin/c++ -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- BUILD_GTESTS: ON`
`-- HIDE_SYMBOL: OFF`
`-- DEBUG_SYMBOL: ON`
`-- not use clang-tidy`
`-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") `
`-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so`
`-- pybind11_INCLUDE_DIRS: /usr/include;/usr/include/python3.6m`
`-- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found version "1.13.3") `
`-- NUMPY_INCLUDE_DIR: /usr/lib/python3/dist-packages/numpy/core/include`
`-- modmesh_INCLUDE_DIR: /usr/include`
`-- modmesh_INCLUDE_DIR: /usr/include`
`-- Performing Test HAS_FLTO`
`-- Performing Test HAS_FLTO - Success`
`-- LTO enabled`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/joe/turgon/spacetime/build/gtests/googletest-download`
`Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (download, verify and extract) for 'googletest'
-- Downloading...
   dst='/home/joe/turgon/spacetime/build/gtests/googletest-download/googletest-prefix/src/release-1.8.1.tar.gz'
   timeout='none'
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.tar.gz'
-- verifying file...
       file='/home/joe/turgon/spacetime/build/gtests/googletest-download/googletest-prefix/src/release-1.8.1.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/joe/turgon/spacetime/build/gtests/googletest-download/googletest-prefix/src/release-1.8.1.tar.gz'
     dst='/home/joe/turgon/spacetime/build/gtests/googletest-src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No patch step for 'googletest'
[ 44%] No update step for 'googletest'
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest`
`-- Looking for pthread.h`
`-- Looking for pthread.h - found`
`-- Looking for pthread_create`
`-- Looking for pthread_create - not found`
`-- Check if compiler accepts -pthread`
`-- Check if compiler accepts -pthread - yes`
`-- Found Threads: TRUE  `
`-- Configuring incomplete, errors occurred!`
`See also "/home/joe/turgon/spacetime/build/CMakeFiles/CMakeOutput.log".`
`See also "/home/joe/turgon/spacetime/build/CMakeFiles/CMakeError.log". `

And the following is content in CMakeError.log.
`Determining if the pthread_create exist failed with the following output:
Change Dir: /home/joe/turgon/spacetime/build/CMakeFiles/CMakeTmp`

`Run Build Command:"/usr/bin/make" "cmTC_8080e/fast"
/usr/bin/make -f CMakeFiles/cmTC_8080e.dir/build.make CMakeFiles/cmTC_8080e.dir/build
make[1]: Entering directory '/home/joe/turgon/spacetime/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8080e.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_8080e.dir/CheckSymbolExists.c.o   -c /home/joe/turgon/spacetime/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_8080e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8080e.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_8080e.dir/CheckSymbolExists.c.o  -o cmTC_8080e 
CMakeFiles/cmTC_8080e.dir/CheckSymbolExists.c.o: 於函式 main:
CheckSymbolExists.c:(.text+0x1b): 未定義參考到 pthread_create
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8080e.dir/build.make:97: recipe for target 'cmTC_8080e' failed
make[1]: *** [cmTC_8080e] Error 1
make[1]: Leaving directory '/home/joe/turgon/spacetime/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8080e/fast' failed
make: *** [cmTC_8080e/fast] Error 2`

`File /home/joe/turgon/spacetime/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>
int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}`

**Comment by yungyuc** [comment]
Thanks @Joechiaotung , could you try to use a newer version of `cmake`?  Version `3.15.4` works but an older one should also do.
